# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Updated the values
name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    env:
      USER: ${{ vars.CSCCUID }}
      ACR_HOST: ${{ vars.ACR }}
      # JOB: ${{ vars.GITHUB_RUN_ATTEMPT }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Check env vars
      run: |
        echo "ACR_HOST: $ACR_HOST"
        echo "CSCCUID: $USER"
        echo "JOB ID: $GITHUB_RUN_ATTEMPT"
    
    - name: log into Azure CR
      uses: azure/docker-login@v1
      with:
        login-server: wiit7501ewagner.azurecr.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker build . -t wiit7501ewagner.azurecr.io/week9-example/$USER:v$GITHUB_RUN_NUMBER
        docker push wiit7501ewagner.azurecr.io/week9-example/$USER:v$GITHUB_RUN_NUMBER
